openapi: 3.0.3
info:
  title: Ollklean API
  version: 1.0.0
security:
  - SecurityHeader: []
paths:
  /codes:
    get:
      operationId: ListCodes
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 200 response
          headers:
            X-Page:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Code'
    post:
      operationId: CreateCode
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeRequest'
        required: true
      responses:
        '201':
          description: 201 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
  /codes/{id}:
    get:
      operationId: GetCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
    patch:
      operationId: PatchCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeRequest'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
    delete:
      operationId: DeleteCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 204 response
  /categories:
    get:
      operationId: ListCategories
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 200 response
          headers:
            X-Page:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      operationId: CreateCategory
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequest'
        required: true
      responses:
        '201':
          description: 201 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /categories/{id}:
    get:
      operationId: GetCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    patch:
      operationId: PatchCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequest'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    delete:
      operationId: DeleteCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 204 response
components:
  securitySchemes:
    SecurityHeader:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Code:
      type: object
      properties:
        id:
          type: integer
          format: int64
        kind:
          type: string
        code:
          type: string
        description:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - kind
        - code
        - description
        - createdBy
        - updatedBy
        - createdAt
        - updatedAt
    CodeRequest:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      required:
        - code
        - description
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        kind:
          type: string
        category:
          type: string
        description:
          type: string
        createdBy:
          type: string
        updatedBy:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - kind
        - category
        - description
        - createdBy
        - updatedBy
        - createdAt
        - updatedAt
    CategoryRequest:
      type: object
      properties:
        category:
          type: string
        description:
          type: string
      required:
        - category
        - description
